In [5]:
import numpy as np
ar1 = np.array(list(range(10)), dtype = int)

In [6]:
len(ar1)

10

In [7]:
ar1.ndim

1

In [8]:
ar1.shape

(10,)

In [12]:
ar1.reshape(5,-1).ndim

2

In [13]:
ar1.reshape(5,-1).shape

(5, 2)

In [15]:
# Club multiple Lists/Range to create an Array
ar2 = np.array([range(1,5),range(5,9),range(9,13)])

In [17]:
ar2.ndim

2

In [18]:
ar2.shape

(3, 4)

In [29]:
ar2.shape = (2,-1)

In [30]:
ar2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [34]:
ar3 = np.arange(1,25)

In [42]:
ar3.reshape(2,1,-1)

array([[[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]],

       [[13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]]])

In [43]:
ar3.itemsize

4

In [44]:
ar1 = np.arange(1,5)
ar2 = np.arange(5,9)

In [45]:
ar1

array([1, 2, 3, 4])

In [46]:
ar2

array([5, 6, 7, 8])

In [48]:
np.add(ar1,ar2)

array([ 6,  8, 10, 12])

In [49]:
np.subtract(ar1,ar2)

array([-4, -4, -4, -4])

In [50]:
np.multiply(ar1,ar2)

array([ 5, 12, 21, 32])

In [51]:
ar1.dot(ar2)

70

In [55]:
ar2.dot(ar1)

70

In [58]:
ar = np.array([ar1,ar2])

In [59]:
ar

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [60]:
np.sum(ar)

36

In [61]:
# Sum of Each Column
np.sum(ar,axis = 0)

array([ 6,  8, 10, 12])

In [62]:
# Sum of Each Row
np.sum(ar,axis = 1)

array([10, 26])

# Week 3 : Assignment

In [71]:
import pandas as pd
db = pd.read_table('Iris_data_sample.txt',index_col = 0,delimiter = " ",usecols=[1,5])

In [91]:
print(db.iloc[-1])
#type(db.tail(1))

SepalLengthCm    150.0
Species            1.8
Name: 150, dtype: float64


In [96]:
#db.loc[:,['Species']]
db['Species']

1      0.2
2      0.2
3      0.2
4      0.2
5      0.2
      ... 
146    2.3
147    1.9
148    2.0
149    2.3
150    1.8
Name: Species, Length: 150, dtype: float64

In [100]:
db

SepalLengthCm  Species
1                1      0.2
2                2      0.2
3                3      0.2
4                4      0.2
5                5      0.2
..             ...      ...
146            146      2.3
147            147      1.9
148            148      2.0
149            149      2.3
150            150      1.8

[150 rows x 2 columns]

In [78]:
db.loc[:,['Species']]

Species
1        0.2
2        0.2
3        0.2
4        0.2
5        0.2
..       ...
146      2.3
147      1.9
148      2.0
149      2.3
150      1.8

[150 rows x 1 columns]

In [98]:
db.iloc[-1]

SepalLengthCm    150.0
Species            1.8
Name: 150, dtype: float64